version: '3'
services:
  mongo:
    image: mongo:6.0.2
    restart: always
    container_name: mongo
    ports:
      - "127.0.0.1:${MONGO_PORT}:${MONGO_PORT}"  # Bind MongoDB to localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: fashion
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - network

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: fashion
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_SITE_BASEURL: /mongo-express
    depends_on:
      - mongo
    ports:
      - "127.0.0.1:${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}" # Bind Mongo Express to localhost
    networks:
      - network

  backend:
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: ${MONGO_PORT}
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
    restart: always
    ports:
      - "127.0.0.1:${BACKEND_PORT}:${BACKEND_PORT}"  # Bind backend to localhost
    networks:
      - network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:${FRONTEND_PORT}:${FRONTEND_PORT}"  # Bind frontend to localhost
    networks:
      - network

networks:
  network:
