version: '3'
services:
  mongo:
    image: mongo:6.0.2
    restart: always
    container_name: mongo
    ports:
      - 127.0.0.1:27017:27017  # Bind MongoDB to localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: fashion
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      - network

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: fashion
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_SITE_BASEURL: /mongo-express
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:8081:8081 # Bind Mongo Express to localhost
    networks:
      - network

  backend:
    environment:
      MONGO_HOST: mongo
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
    restart: always
    ports:
      - 127.0.0.1:4567:4567  # Bind backend to localhost
    networks:
      - network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 127.0.0.1:3000:3000  # Bind frontend to localhost
    networks:
      - network

networks:
  network: